### ISSUE TITLE
Bug Report: wiki cipher button in shown in all editiors, not only in wiki page editor.

### ISSUE THREAD

**Issue by cforce** [keeps/redmine_wikicipher#15]

**Comment by sleroux-keep** [comment]
I think the commit 3b377e4e2e4fee593f086360c9492f35770430df fixes this issue.

**Comment by hsilva-keep** [comment]
Minor update: it was fully fixed in 6597cbb7cc94f08bcda74a334b55a5186429b241. Closing this issue.
