### ISSUE TITLE
*abc* inside a cipher tag should NOT show as bold

### ISSUE THREAD

**Issue by ghost** [keeps/redmine_wikicipher#16]
If you write text *abc* and cipher it, the markup will be {{cipher}}*abc*{{cipher}} but when you decipher it will show as **abc** inside the {{cipher}} tags.

**Comment by sleroux-keep** [comment]
I've added <notextile> tags when showing the decrypted version (23ad45223fe16e33cf4a174d700b68a7bd2609b5) . I think it's working fine...

**Comment by hsilva-keep** [comment]
Yes, as @sleroux-keep pointed out, in commit 23ad45223fe16e33cf4a174d700b68a7bd2609b5 this was fixed by wrapping the decoded text in the tag \<notextile\>. Closing this issue.
