### ISSUE TITLE
problems with redmine 2.4.3

### ISSUE THREAD

**Issue by Freagle72** [keeps/redmine_wikicipher#17]
Hallo, 

I got a problem at installing you plugin at a redmine 2.4.3. After saving an exisiting wiki page I got an Internal error 500 by the web server.

The error_log at apache show these error code:

Started GET "/projects/swp/wiki/SEPA/edit" for 194.116.xxx.xx at 2014-02-13 12:55:27 +0100
Processing by WikiController#edit as HTML
  Parameters: {"project_id"=>"swp", "id"=>"SEPA"}
  Current user: j.spegel@swp.de (id=7)
  Rendered attachments/_form.html.erb (7.9ms)
  Rendered wiki/edit.html.erb within layouts/base (345.7ms)
  Rendered plugins/redmine_private_wiki/app/views/hooks/_html_header.html.erb (0.8ms)
  Rendered plugins/redmine_wikicipher/app/views/hooks/redmine_wikicipher/_includes.html.erb (1.8ms)
  Rendered plugins/redmine_private_wiki/app/views/hooks/_body_bottom.html.erb (1.1ms)
Completed 200 OK in 595.1ms (Views: 558.3ms | ActiveRecord: 10.9ms)
Started PUT "/projects/swp/wiki/SEPA" for 194.116.207.65 at 2014-02-13 12:55:36 +0100
Processing by WikiController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=", "content"=>{"version"
=>"3", "text"=>"[FILTERED]", "comments"=>""}, "wiki_page"=>{"parent_id"=>"2"}, "commit"=>"Speichern", "project_id"=>"sw
p", "id"=>"SEPA"}
  Current user: xxx@xxx.de (id=7)
redmine 2.X
Completed 500 Internal Server Error in 32.1ms

ArgumentError (wrong number of arguments (0 for 1)):
  app/models/wiki_page.rb:178:in `save_with_content'

So I fixed your redmine_wikicipher/lib/wiki_controller_patch.rb to correct the problem:

<pre>
--- a/lib/wiki_controller_patch.rb
+++ b/lib/wiki_controller_patch.rb
@@ -302,7 +302,7 @@ return render_403 unless editable?
 
     @content.text = encode(@content.text,params,0)
 
-    if @page.save_with_content
+    if @page.save_with_content(@content)
       attachments = Attachment.attach_files(@page, params[:attachments])
       render_attachment_warning_if_needed(@page)
       call_hook(:controller_wiki_edit_after_save, { :params => params, :page => @page})
</pre>

Maybe these information above help you to develop your very usefull plugin.

Best regards, Joe

**Comment by hsilva-keep** [comment]
This has been fixed in 464ca030cb05d9d131388f53fe18db9805db30b9. Closing the issue.
