### ISSUE TITLE
Add "cypher" option to Roles & Permissions

### ISSUE THREAD

**Issue by dani-sanchez-dorado** [keeps/redmine_wikicipher#18]
Hello!
I have test the cipher plug-in, and it works fine, but, we think that would be more usable with a modification.
Now, everybody that can access to the wiki pages, can decrypt the content. I think that it would be fantastic that we could control who can see the content. 
The solution would be to include the "Decrypt" Role in the redmine installation, and then, the administrator could choose witch role can decrypt or not. 

Thank you very much!

**Comment by hsilva-keep** [comment]
@dani-sanchez-dorado @exc305 First of all, please accept our apologies for the late answer. 

I do agree with you guys that this would be a nice feature to have. But ATM we can't allocate internal effort to do this as we don't see it as a really needed feature/improvement.

I'll close the issue for now, but if you want to contribute please do it in the form of pull request (and please re-open this issue or post a new one). The community (us included) would appreciate it.
