### ISSUE TITLE
Special chars should be properly escaped when showing the decrypted version 

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/redmine_wikicipher#22]
Characters like pipes ('|') and others (special chars in textile) should be properly escaped when showing the decrypted version of the text, otherwise they mess up with visual output.
E.g. (table with two columns):
| column 1 | column 2 |
| text 1 | text 2 |
| lala | {{cipher}}ajsdhkas|daskjd{{cipher}} |

**Comment by sleroux-keep** [comment]
I've added <notextile> tags when showing the decrypted version (23ad45223fe16e33cf4a174d700b68a7bd2609b5) . I think it's working fine...

**Comment by hsilva-keep** [comment]
Yes, as @sleroux-keep pointed out, in commit 23ad45223fe16e33cf4a174d700b68a7bd2609b5 this was fixed by wrapping the decoded text in the tag \<notextile\>. Closing this issue.
