### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by cforce** [keeps/redmine_wikicipher#8]
After using any wiki cipher block in a wiki site i can 'use the wiki history compare or show method for this site change without error.
As soo as i i try to compate this site or show the historic change i get an error. I dont't have this problem when i don't use the cyper macro in the site.

ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
    39:     <hr />
    40: <% end %>
    41: 
    42: <%= render(:partial => "wiki/content", :locals => {:content => @content}) %>
    43: 
    44: <%= link_to_attachments @page %>
    45: 
  activesupport (3.2.11) lib/active_support/core_ext/string/output_safety.rb:133:in `concat'
  activesupport (3.2.11) lib/active_support/core_ext/string/output_safety.rb:133:in `concat'
  actionpack (3.2.11) lib/action_view/buffers.rb:11:in `<<'
  plugins/redmine_wikicipher/app/views/wiki/show.html.erb:42:in `_plugins_redmine_wikicipher_app_views_wiki_show_html_erb__972499250_116039270'
  actionpack (3.2.11) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.11) lib/active_support/notifications.rb:125:in `instrument'

**Comment by hsilva-keep** [comment]
As no extra feedback was provided upon changes made to solve the issue, I'm assuming that it has been fixed. I'll close this issue for now (if problems still persists please re-open the issue or post a new one).
